### ISSUE TITLE
How to use the output

### ISSUE THREAD

**Issue by edmundhighcock** [SwitchQL/SwitchQL#45]
Dear SwitchQL,

I have successfully updated the branch ian/mysql to work with mysql and will submit a PR soon. However, being an apollo newbie, I don't know how to turn the generated code into a GraphQL server... any pointers would be much appreciated!

Thanks, 

Edmund

**Comment by rob2244** [comment]
Hi Edmund, 
Thank you so much for checking out our project and contributing!

We plan to add instructions to the read-me for how to get the server started, but in the mean time here's what to do.

To configure the Graph QL Server:

1) Create a new node project using npm or yarn. 
2) Ceate a src/ directory and in your project add the files that were generated by switch ql
3) Add a file called server.js in the src directory
4) Install the following npm packages: express, express-graphql, graphql-iso-date, graphql, and mysql
5) Copy the following code into the server.js file 
```javascript
var express = require("express");
var graphqlHTTP = require("express-graphql");
var schema = require("./Schema");

var app = express();
app.use(
  "/graphql",
  graphqlHTTP({
    schema,
    graphiql: true
  })
);
app.listen(4000);
console.log("Running a GraphQL API server at localhost:4000/graphql");
```
6. Run: node src/server.js from the command line and your server should be up and running.

To configure the Apollo client:
1. Install the following npm packages: apollo-boost, and node-babel
2. Create a new javascript file in your src folder called client.js
3. Copy the following code into it
```javascript 
const apollo = require("apollo-boost");
const clientQueries = require("./clientQueries");
const clientMutations = require("./clientMutations");

const client = new apollo.ApolloClient({
  uri: "https://localhost:4000/graphql"
});
```
4. You can now use the query function on the apollo client to query your running graphql server
e.g.
```javascript
const apollo = require("apollo-boost");
const clientQueries = require("./clientQueries");
const clientMutations = require("./clientMutations");

const client = new apollo.ApolloClient({
  uri: "https://localhost:4000/graphql"
});

client.query(clientQueries.queryEveryAuthor).then(console.log);
```
You can also pass the query function mutations and parameters as well.
More documentation is available on the apollo website: 
https://www.apollographql.com/docs/react/api/apollo-client/

5. To run the client file you have to use node-babel because the client mutations and client queries use the es6 import syntax. You would run it in the command line like this: node-babel src/client.js

I hope this helps, and feel free to contact us if you have any more questions!

**Comment by laueian** [comment]
You can also clone this [repo](https://github.com/laueian/graphQL-node) as graphql server boilerplate :)

**Comment by edmundhighcock** [comment]
Thanks for all the help! I've submitted a pull request for my fixes to the MySQL option... feel free to ask questions.

**Comment by laueian** [comment]
Awesome! We'll take a look ASAP
