### ISSUE TITLE
mssql server

### ISSUE THREAD

**Issue by sabond** [SwitchQL/SwitchQL#64]
I'm just curious if Release 1.0 should be connecting to MSSQL server.  I've attempted it many times, different options to connect string, without connect string, using input boxes with different inputs.  I can't connect to MSSQL Server.

I haven't tried PostGresSQL, but really need MSSQL to work, and thought your app was a God send.  

Any suggestions or help would be much appreciated.  Thks!

**Comment by rob2244** [comment]
@sabond first of all thank you so much for trying the app! Release 1.0 only does postgres. However the mssql provider is pretty much finished in the dev branch. There's one very blatant outstanding issue that I need to make a pr to fix, but I can do that tonight. I can build an exe off the dev branch if you let me know what platform you're using and send it to you after it's fixed. Or if you're comfortable building it yourself I can let you know when the fix is in and you can clone the repo.

Thanks!

**Comment by sabond** [comment]
@rob2244 

Thanks for the quick response!  I'm on win64 platform, but I'm comfortable with cloning the dev branch once the fix has been applied.  I sure do appreciate your help!

Thks!

**Comment by rob2244** [comment]
@sabond Fix should be in dev.
Just a few notes:
- There may still be a lot of bugs in the application, please report any you find and we'll fix them as quickly as possible
- Feel free to use the generated code as a starting point, but please don't use it in production without double checking it
- You can run the npm pack and npm dist commands to create an exe for your os
- we don't generate a package json for you automatically yet, so you'll need to npm install the following packages when when using the generated code: mssql, graphql, graphql-iso-date, apollo-boost
- We do support spaces in table names but not in column names
- The application should support all common sql scalar data types, but less common ones like picture may throw an exception (we have an open ticket for this)
- Currently we don't have a good way of handling many to many relationships so we instead handle them as multiple one to many relationships (we're working on this)
- For the generated mssql code you will need to create a pool connection yourself and pass it to schema.js
e.g.
```javascript
const express = require("express");
const graphqlHTTP = require("express-graphql");
const schema = require("./Schema");
const sql = require("mssql");

(async () => {
  const conn = await new sql.ConnectionPool(
    "mssql://{username}:{password}@{hostname}:1433/{database}?encrypt=true&request%20timeout=30000"
  ).connect();
  const sch = schema(conn);

  const app = express();

  app.use(
    "/graphql",
    graphqlHTTP({
      schema: sch,
      graphiql: true
    })
  );

  app.listen(4000, () => {
    console.log("Running a GraphQL API server at localhost:4000/graphql");
  });
})();
```
- Feature requests are welcome

Thanks!

**Comment by laueian** [comment]
@sabond Hey, were you able to get everything up and running? Did you have a good experience using SwitchQL?

**Comment by sabond** [comment]
Ian -

No, I've not been able to connect to either postgresql or mssql databases.
I've tried all
methods via the electron app, but no joy.

I can connect to both using different methods, but can't connect using
SwitchQL.

I've been too busy with work to really explore switchQL and why it's not
connecting.

Thank you for your inquiry!
Steve

**Comment by rob2244** [comment]
@sabond , 
I'm sorry you're having trouble running the project. When you have some time could you pull the latest and give it one more try. I realized I introduced some new bugs the last time I told you to pull it. I've since fixed them and merged the changes to dev. Barring that, you can try to run the project in debug and let us know where it's throwing an exception, not ideal I know, but unfortunately we haven't had a chance to add file logging yet.
Thanks!

-Robin

**Comment by sabond** [comment]
Robin - 
I pulled the latest dev and it's connecting now.  I haven't a chance to really analyze the output yet, but plan to do so when time allows.  What I've seen looks impressive!  Thank you for your time & efforts!

-Steve
